# Generated by Django 4.0.4 on 2022-04-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='points',
        ),
    ]
